/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package max;

import org.junit.Test;
import java.util.*;
import static org.junit.Assert.*;

public class MaxSubArrayValsOfLenKTest{
    
    @Test public void testSolveQuadratic() {
       MaxSubArrayValsOfLenK solver = new MaxSubArrayValsOfLenK();
       assertEquals(Arrays.asList(10,7,8,8), solver.solveQuadratic(new int[]{10, 5, 2, 7, 8, 7}, 3));  
    }
    
}
