/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sum;

import java.util.*;

public class SumTwoEqualsK {
    
    /**
     * Brute force solution O(n^2)
     */
    public boolean satisfiesBrute(int[] nums, int k){

        for(int i = 0; i < nums.length-1; i++){
            for( int j = i + 1; j < nums.length; j++){
                if( nums[i] + nums[j] == k ){
                    return true;
                }
            }
        }
        return false;

    }
   
}
