/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedlist;

import org.junit.Test;
import java.util.*;
import static org.junit.Assert.*;

public class LinkedListIntersectionTest{
    

	@Test
	public void testGetIntersection_UnequalLengthLists_1(){
		LinkedListIntersection solver = new LinkedListIntersection();
		Node shared = Node.of(new int[]{1,2,3});

		Node a = Node.of(new int[]{4,5}).append(shared);
		Node b = shared;
		
		assertEquals(shared, solver.findIntersection(a,b));
	}

	@Test
	public void testGetIntersection_UnequalLengthLists_2(){
		LinkedListIntersection solver = new LinkedListIntersection();
		Node shared = Node.of(new int[]{1,2,3});

		Node a = Node.of(new int[]{4,5}).append(shared);
		Node b = Node.of(new int[]{1,2,3,5}).append(shared);
     
		assertEquals(shared, solver.findIntersection(a,b));
	}

	@Test
	public void testGetIntersection_EqualLengthLists(){
		LinkedListIntersection solver = new LinkedListIntersection();
		Node shared = Node.of(new int[]{1,2,3});

		Node a = Node.of(new int[]{4,5}).append(shared);
		Node b = Node.of(new int[]{7,2}).append(shared);
		
		assertEquals(shared, solver.findIntersection(a,b));

	}
    
}
