/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package staircase;

import org.junit.Test;
import java.util.*;
import static org.junit.Assert.*;

public class StairCaseExtendedTest {
    

    @Test public void test_CountWays() {
        StairCaseExtended stairCase = new StairCaseExtended();
        assertEquals(5, stairCase.countWays(4, Arrays.asList(1,2)));
        assertEquals(3, stairCase.countWays(4, Arrays.asList(1,3)));
        assertEquals(0, stairCase.countWays(4, Arrays.asList(3)));
        assertEquals(0, stairCase.countWays(4, Arrays.asList(3)));
        assertEquals(1, stairCase.countWays(4, Arrays.asList(2)));
    }
}
