/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package staircase;

import org.junit.Test;
import java.util.*;
import static org.junit.Assert.*;

public class StairCaseTest {
    

    @Test public void test_CountWays() {
        StairCase stairCase = new StairCase();
        assertEquals(5, stairCase.countWays(4));
    }
}
