/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedlist;

import java.util.*;
import java.lang.Math;

public class LinkedListIntersection {
   
   public Node findIntersection(Node a, Node b){

   	int aLen = Node.length(a);
   	int bLen = Node.length(b);
   	int absDiff = Math.abs(aLen-bLen);

   	Node aCurr = a;
   	Node bCurr = b;
   	if( absDiff > 0 ){
		if( aLen > bLen ){
			aCurr = aCurr.getIth(absDiff);
		} else {
			bCurr = bCurr.getIth(absDiff);
		}
	
   	}
	while( aCurr != bCurr ){
		aCurr = aCurr.next;
		bCurr = bCurr.next;
	}
	return aCurr;
   }
   
   
}      

