/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package staircase;

import java.util.*;

public class StairCase {
    
    /**
     * Gets the total number of ways to hop the stairs given
     * you can hop either 1 or 2 stairs at a time
     */ 
    public int countWays(int steps) {
    	if( steps == 0 ){
    		return 1; 
    	}

    	if( steps < 0 ){
    		return 0;
    	}

        return countWays(steps-1) + countWays(steps-2);
    }
}
